apiVersion: apps/v1
kind: Deployment
metadata:
 name: nodejs-web
 labels:
   app: nodejs-web
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nodejs-web
  template:
    metadata:
      labels:
        app: nodejs-web
    spec:
     containers:
     - name: nodejs-web
       image: public.ecr.aws/j1z0f1m9/nodjs-web:1.5
       ports:
       - name: http-port
         containerPort: 80
