apiVersion: v1
kind: Pod
metadata:
  name: nodejs-web
  labels:
    app: nodejs-web
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: nodejs-web
      image: public.ecr.aws/j1z0f1m9/nodjs-web:latest
      imagePullPolicy: Always
